// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kekbrdusfdzwnxhxuocb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtla2JyZHVzZmR6d254aHh1b2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjE3MzUsImV4cCI6MjA2ODczNzczNX0.eBPcFPegkXDbycsy5nHMgdROGRwuJ1K8JMg4NU2U4xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});